### ISSUE TITLE
api to upload to nginx-image-server ?

### ISSUE THREAD

**Issue by Alino** [wantedly/nginx-image-server#38]
hi, is there some api?
I would like to be able to upload images to nginx-image-server's image directory via some api.
What is your approach? Thank you

**Comment by luvtechno** [comment]
@Alino Here at Wantedly, we don't upload images to S3 through nginx-image-server. Clients (browsers and mobile apps) directly uploads to S3 using policy and signature issued by API server. Hope this helps.

**Comment by Alino** [comment]
thank you for answer.

If someone is still interested in making it possible to upload images to nginx-image-server, you might get inspired from my fork -> https://github.com/Alino/nginx-image-server/commit/1b0f9263880d26531f91e0911200d2d332e0d761
