### ISSUE TITLE
how to display svg files?

### ISSUE THREAD

**Issue by Alino** [wantedly/nginx-image-server#40]
if I have an svg file inside `/var/www/nginx-image-server/images` with this example content http://pastebin.com/Zs8tbqmX

if I try to open it in a browser via nginx-image-server
`http://127.0.0.1:3005/local/small_light(dw=200)/images/my_image.svg`
**then I see a blank page**  - I should see the image

other image file types (jpegs, pngs) work.

**Comment by cubicdaiya** [comment]
Now ngx_small_light does not support SVG.

https://github.com/cubicdaiya/ngx_small_light#supported-formats

**Comment by Alino** [comment]
thank you for quick response.

**Comment by aztech-dev** [comment]
Additionnally, SVG is stored as text regardless of its rendered size, so there are no real benefits to using a resizing module. Any decent modern browser will handle the format fine and render it to whatever size you specify in your webpage.
